export const mainPage = {
    title: 'Featured <span>Works</span>',
    elements: [
        {
            id: 1,
            client: `SKYWORLD LINK TRAVELS`,
            src: `/images/DuceWeb-Sky_link_World_Travel_and_Tourism_Agency_website_design.png`,
            alt: `Skyworld Link Travels and tourism website UI/UX design template by DuceWeb`,
            width: 1000,
            height: 475,
            title: `Cliente: Skyworld Link Travels`,
            link: `skyworld-link-travels`,
        },
        {
            id: 2,
            client: `WOWFACTORBYREMIX`,
            src: `/images/DuceWeb-WOW_Factor_By_Remix.png`,
            alt: `WOW Factor by Remix website UI/UX design template`,
            width: 1000,
            height: 475,
            title: `Cliente: Wow Factor By Remix`,
            link: `wow-factor-by-remix`,
        },
        {
            id: 3,
            client: `BEEOLIX ENTERPRISE`,
            src: `/images/DuceWeb-Beeolix_Fashion_Brand_Website_design_and_development.png`,
            alt: `Beeolix Fashion Enterprise website UI/UX design template by DuceWeb`,
            width: 1000,
            height: 475,
            title: `Cliente: Beeolix Fashion ENterprise`,
            link: `beeolix`,
        },
        {
            id: 4,
            client: `ASKSHOLA`,
            src: `/images/DuceWeb-Askshola.png`,
            alt: `AskShola personal portfolio UI/UX designed by DuceWeb`,
            width: 1000,
            height: 475,
            title: `Cliente: AskShola`,
            link: `askshola`,
        },
        {
            id: 5,
            client: `GROK BRAND`,
            src: `/images/DuceWeb-Grok_brand.png`,
            alt: `Grok Brand website UI/UX designed by DuceWeb`,
            width: 1000,
            height: 475,
            title: `Cliente: Grok Brand`,
            link: `grok-brand`,
        },
        {
            id: 6,
            client: `POSFIK LUXURY`,
            src: `/images/DuceWeb-Pofluxury.png`,
            alt: `Pofluxury fashion website UI/UX designed by DuceWeb`,
            width: 1000,
            height: 475,
            title: `Cliente: POSFIK by POF Luxury`,
            link: `pofluxury`,
        },
    ]
    
}